language: go

go:
  - "1.x"
  - "1.10"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get github.com/mattn/goveralls

script: $GOPATH/bin/goveralls -service=travis-ci 
